version: "3.0"

services: 
  mysql:
    image: mysql
    environment: 
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
#             - MYSQL_DATABASE=dapi_assg_db
#       - MYSQL_USER=dan
#       - MYSQL_PASSWORD=secret
#       - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    container_name: mysql_db
    
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: node-mysql
    restart: always
    
    ports:
      - '9898:9898'
    environment: 
      - DB_HOST=mysql_db
      - DB_NAME=mysqldb
      - DB_USER=user
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    container_name: nodejs
    depends_on: 
      - mysql
    
#     user: process.env.DB_USER,
#     password: process.env.DB_PASSWORD,
#     database: process.env.DB_NAME
    
