version: "3.0"

services: 
  mysql:
    image: mysql
    environment: 
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    container_name: mysql
    
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: node-mysql
    restart: always
    
    ports:
      - '9898:9898'
    environment: 
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    container_name: nodejs
    
